#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v10
# autospec commit: 5905be9
#
# Source0 file verified with key 0x88953E6F011CDC96 (doug@uq.edu.au)
#
Name     : NetworkManager-l2tp
Version  : 1.20.16
Release  : 13
URL      : https://github.com/nm-l2tp/NetworkManager-l2tp/releases/download/1.20.16/NetworkManager-l2tp-1.20.16.tar.xz
Source0  : https://github.com/nm-l2tp/NetworkManager-l2tp/releases/download/1.20.16/NetworkManager-l2tp-1.20.16.tar.xz
Source1  : https://github.com/nm-l2tp/NetworkManager-l2tp/releases/download/1.20.16/NetworkManager-l2tp-1.20.16.tar.xz.asc
Source2  : 88953E6F011CDC96.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: NetworkManager-l2tp-data = %{version}-%{release}
Requires: NetworkManager-l2tp-lib = %{version}-%{release}
Requires: NetworkManager-l2tp-libexec = %{version}-%{release}
Requires: NetworkManager-l2tp-license = %{version}-%{release}
Requires: NetworkManager-l2tp-locales = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : file
BuildRequires : gettext
BuildRequires : gnupg
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(gtk4)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libnm)
BuildRequires : pkgconfig(libnma)
BuildRequires : pkgconfig(libnma-gtk4)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : pkgconfig(nss)
BuildRequires : pkgconfig(pppd)
BuildRequires : ppp-dev
BuildRequires : pypi(packaging)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
The files in the "shared/" directory are used by all components
inside the VPN plugin repository (src, properties, auth-dialog).

%package data
Summary: data components for the NetworkManager-l2tp package.
Group: Data

%description data
data components for the NetworkManager-l2tp package.


%package lib
Summary: lib components for the NetworkManager-l2tp package.
Group: Libraries
Requires: NetworkManager-l2tp-data = %{version}-%{release}
Requires: NetworkManager-l2tp-libexec = %{version}-%{release}
Requires: NetworkManager-l2tp-license = %{version}-%{release}

%description lib
lib components for the NetworkManager-l2tp package.


%package libexec
Summary: libexec components for the NetworkManager-l2tp package.
Group: Default
Requires: NetworkManager-l2tp-license = %{version}-%{release}

%description libexec
libexec components for the NetworkManager-l2tp package.


%package license
Summary: license components for the NetworkManager-l2tp package.
Group: Default

%description license
license components for the NetworkManager-l2tp package.


%package locales
Summary: locales components for the NetworkManager-l2tp package.
Group: Default

%description locales
locales components for the NetworkManager-l2tp package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 88953E6F011CDC96' gpg.status
%setup -q -n NetworkManager-l2tp-1.20.16
cd %{_builddir}/NetworkManager-l2tp-1.20.16
pushd ..
cp -a NetworkManager-l2tp-1.20.16 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1715782170
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1715782170
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/NetworkManager-l2tp
cp %{_builddir}/NetworkManager-l2tp-%{version}/COPYING %{buildroot}/usr/share/package-licenses/NetworkManager-l2tp/4cc77b90af91e615a64ae04893fdffa7939db84c || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
%find_lang NetworkManager-l2tp
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib/NetworkManager/VPN/nm-l2tp-service.name

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/system.d/nm-l2tp-service.conf
/usr/share/metainfo/network-manager-l2tp.metainfo.xml

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/NetworkManager/libnm-vpn-plugin-l2tp-editor.so
/V3/usr/lib64/NetworkManager/libnm-vpn-plugin-l2tp.so
/V3/usr/lib64/pppd/2.5.0/nm-l2tp-pppd-plugin.so
/usr/lib64/NetworkManager/libnm-vpn-plugin-l2tp-editor.so
/usr/lib64/NetworkManager/libnm-vpn-plugin-l2tp.so
/usr/lib64/pppd/2.5.0/nm-l2tp-pppd-plugin.so

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/nm-l2tp-auth-dialog
/V3/usr/libexec/nm-l2tp-service
/usr/libexec/nm-l2tp-auth-dialog
/usr/libexec/nm-l2tp-service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/NetworkManager-l2tp/4cc77b90af91e615a64ae04893fdffa7939db84c

%files locales -f NetworkManager-l2tp.lang
%defattr(-,root,root,-)

