#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x49A7787EF8D3C039 (doug@uq.edu.au)
#
Name     : NetworkManager-l2tp
Version  : 1.2.16
Release  : 2
URL      : https://github.com/nm-l2tp/NetworkManager-l2tp/releases/download/1.2.16/NetworkManager-l2tp-1.2.16.tar.xz
Source0  : https://github.com/nm-l2tp/NetworkManager-l2tp/releases/download/1.2.16/NetworkManager-l2tp-1.2.16.tar.xz
Source1 : https://github.com/nm-l2tp/NetworkManager-l2tp/releases/download/1.2.16/NetworkManager-l2tp-1.2.16.tar.xz.asc
Summary  : L2TP support for NetworkManager
Group    : Development/Tools
License  : GPL-2.0
Requires: NetworkManager-l2tp-data = %{version}-%{release}
Requires: NetworkManager-l2tp-lib = %{version}-%{release}
Requires: NetworkManager-l2tp-libexec = %{version}-%{release}
Requires: NetworkManager-l2tp-license = %{version}-%{release}
Requires: NetworkManager-l2tp-locales = %{version}-%{release}
BuildRequires : gettext
BuildRequires : intltool
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(NetworkManager)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libnm)
BuildRequires : pkgconfig(libnm-glib)
BuildRequires : pkgconfig(libnm-glib-vpn)
BuildRequires : pkgconfig(libnm-gtk)
BuildRequires : pkgconfig(libnm-util)
BuildRequires : pkgconfig(libnma)
BuildRequires : pkgconfig(libsecret-1)
BuildRequires : ppp-dev
BuildRequires : util-linux

%description
The files in the "shared/" directory are used by all components
inside the VPN plugin repository (src, properties, auth-dialog).

%package data
Summary: data components for the NetworkManager-l2tp package.
Group: Data

%description data
data components for the NetworkManager-l2tp package.


%package lib
Summary: lib components for the NetworkManager-l2tp package.
Group: Libraries
Requires: NetworkManager-l2tp-data = %{version}-%{release}
Requires: NetworkManager-l2tp-libexec = %{version}-%{release}
Requires: NetworkManager-l2tp-license = %{version}-%{release}

%description lib
lib components for the NetworkManager-l2tp package.


%package libexec
Summary: libexec components for the NetworkManager-l2tp package.
Group: Default
Requires: NetworkManager-l2tp-license = %{version}-%{release}

%description libexec
libexec components for the NetworkManager-l2tp package.


%package license
Summary: license components for the NetworkManager-l2tp package.
Group: Default

%description license
license components for the NetworkManager-l2tp package.


%package locales
Summary: locales components for the NetworkManager-l2tp package.
Group: Default

%description locales
locales components for the NetworkManager-l2tp package.


%prep
%setup -q -n NetworkManager-l2tp-1.2.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1572882269
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1572882269
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/NetworkManager-l2tp
cp %{_builddir}/NetworkManager-l2tp-1.2.16/COPYING %{buildroot}/usr/share/package-licenses/NetworkManager-l2tp/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1
%make_install
%find_lang NetworkManager-l2tp

%files
%defattr(-,root,root,-)
/usr/lib/NetworkManager/VPN/nm-l2tp-service.name

%files data
%defattr(-,root,root,-)
/usr/share/appdata/network-manager-l2tp.metainfo.xml
/usr/share/dbus-1/system.d/nm-l2tp-service.conf

%files lib
%defattr(-,root,root,-)
/usr/lib64/NetworkManager/libnm-vpn-plugin-l2tp-editor.so
/usr/lib64/NetworkManager/libnm-vpn-plugin-l2tp.so
/usr/lib64/pppd/2.4.7/nm-l2tp-pppd-plugin.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/nm-l2tp-auth-dialog
/usr/libexec/nm-l2tp-service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/NetworkManager-l2tp/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1

%files locales -f NetworkManager-l2tp.lang
%defattr(-,root,root,-)

